### ISSUE TITLE
Ajustes no projeto

### ISSUE THREAD

**Issue by acenelio** [brunofariasdeo/dsproject#1]
Olá Bruno,

Parabéns pelo trabalho. Apenas dois detalhes precisam de correção:

1) Seu endpoint de update não está atualizando e está retornando erro 500 quando informado um id que não existe. Faltou copiar os dados do dto para a entidade obtida com o getOne, e faltou lançar a exceção ResourceNotFoundException caso o id não exista. Favor verificar.

2) Para sumir o erro da dependência de testes, favor acrescentar a seguinte dependência no seu pom.xml:

```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
```

**Comment by brunofariasdeo** [comment]
@acenelio ,

Eu resolvi o problema da dependência de testes no commit [af5b5ce](https://github.com/brunofariasdeo/dsproject/commit/af5b5ce7a445b0cfdd6b7a329adbb3f7aabe0161) e a questão do endpoint de update foi corrigida através do commit [1f2f339](https://github.com/brunofariasdeo/dsproject/commit/1f2f339e372e72d594fc5c98af6471d47ed17ae3).

Muito obrigado pelo feedback! :)
